name             'desktop'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures desktop'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'git'
depends 'ruby_build'
depends 'ruby_rbenv'
depends 'apt'
depends 'postgresql'
depends 'mysql'
depends 'redisio'
